### ISSUE TITLE
vp9 encoder returns null packets

### ISSUE THREAD

**Issue by githubquestions** [DiamondLovesYou/rust-vpx#4]
Going through old webm recorder that uses [fork](https://github.com/kornelski/rust-vpx). Created an issue [there](https://github.com/quadrupleslap/srs/issues/6), but seems like project is not longer maintained. This of course will be difficult to answer, but thought couldn't hurt to see if you might have any ideas as to why `vpx_codec_get_cx_data` returning null. Thanks!

**Comment by DiamondLovesYou** [comment]
Sorry, not a clue. You should probably ask vpx project directly. This project is mostly just a FFI for Rust.

**Comment by githubquestions** [comment]
Okay thank you for the quick response!

**Comment by githubquestions** [comment]
Do you know where to contact vpx? Organization does not seem to use Github and not seeing an official channel?

**Comment by DiamondLovesYou** [comment]
Nope, sorry!
